# Generated by Django 3.2.16 on 2023-01-02 10:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_post_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post1',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
