# Generated by Django 3.2.16 on 2023-01-02 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_post_post1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post1',
        ),
    ]
