# Generated by Django 3.2.16 on 2023-01-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_account_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='account',
            new_name='account_name',
        ),
    ]
