# Generated by Django 3.2.16 on 2023-01-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.CharField(default='abc', max_length=100, unique=True),
        ),
    ]
