# Generated by Django 3.2.16 on 2023-01-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_alter_account_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
