# Generated by Django 3.2.16 on 2023-01-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_auto_20230106_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
