# Generated by Django 3.2.16 on 2023-01-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_auto_20230106_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
