# Generated by Django 3.2.16 on 2023-01-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_alter_comment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=224, null=True),
        ),
    ]
